## Importing Libraries

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Data Preprocessing

In [4]:
dataset = pd.read_csv("./Dataset/Churn_Modelling.csv")
X = dataset.iloc[:, 3:-1].values
Y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(Y)

[1 0 1 ... 1 1 0]


Encoding Gender

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

Encoding Geography

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ot = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ot.fit_transform(X))

Splitting Dataset

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

## Building ANN

In [17]:
ann = tf.keras.models.Sequential()

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [20]:
ann.add(tf.keras.layers.Dense(units= 6, activation='relu'))

In [21]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Compiling

In [22]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

## Training

In [23]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 658us/step - loss: 0.5838 - accuracy: 0.7606
Epoch 2/100
250/250 [==============================] - 0s 608us/step - loss: 0.4959 - accuracy: 0.7949
Epoch 3/100
250/250 [==============================] - 0s 718us/step - loss: 0.4596 - accuracy: 0.7971
Epoch 4/100
250/250 [==============================] - 0s 598us/step - loss: 0.4381 - accuracy: 0.8051
Epoch 5/100
250/250 [==============================] - 0s 586us/step - loss: 0.4233 - accuracy: 0.8125
Epoch 6/100
250/250 [==============================] - 0s 593us/step - loss: 0.4093 - accuracy: 0.8221
Epoch 7/100
250/250 [==============================] - 0s 592us/step - loss: 0.3943 - accuracy: 0.8326
Epoch 8/100
250/250 [==============================] - 0s 577us/step - loss: 0.3801 - accuracy: 0.8416
Epoch 9/100
250/250 [==============================] - 0s 606us/step - loss: 0.3700 - accuracy: 0.8449
Epoch 10/100
250/250 [==============================] - 0s 606us/step - l

In [27]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5

1/1 [==============================] - 0s 12ms/step


array([[False]])

In [28]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 482us/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 1]
 [0 1]]


In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1520   87]
 [ 197  196]]


0.858